
package com.ctl.as.domain.geo.v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.ctl.as.domain.geo.types.request.ClcSearchResourceProxyRequest;
import com.ctl.as.domain.geo.types.request.GetParsedAddressRequest;
import com.ctl.as.domain.geo.types.request.GetServiceAddressLiveRequest;
import com.ctl.as.domain.geo.types.request.GetServiceAddressRequest;
import com.ctl.as.domain.geo.types.request.GetSubAddressesRequest;
import com.ctl.as.domain.geo.types.request.IsThisAddressServiceableRequest;
import com.ctl.as.domain.geo.types.request.SubscriberAddressInquiryProxyRequest;
import com.ctl.as.domain.geo.types.request.ValidateCivicAddressProxyRequest;
import com.ctl.as.domain.geo.v2.types.request.CivicAddressValidationRequest;
import com.ctl.as.domain.geo.v2.types.request.PostalAddressValidationRequest;
import com.ctl.as.domain.geo.v2.types.response.CivicAddressValidationResponse;
import com.ctl.as.domain.geo.v2.types.response.ClcSearchResourceProxyResponse;
import com.ctl.as.domain.geo.v2.types.response.GetParsedAddressResponse;
import com.ctl.as.domain.geo.v2.types.response.GetServiceAddressLiveResponse;
import com.ctl.as.domain.geo.v2.types.response.GetServiceAddressResponse;
import com.ctl.as.domain.geo.v2.types.response.GetSubAddressesResponse;
import com.ctl.as.domain.geo.v2.types.response.IsThisAddressServiceableResponse;
import com.ctl.as.domain.geo.v2.types.response.PostalAddressValidationResponse;
import com.ctl.as.domain.geo.v2.types.response.SubscriberAddressInquiryProxyResponse;
import com.ctl.as.domain.geo.v2.types.response.ValidateCivicAddressProxyResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AddressServiceContract", targetNamespace = "http://geo.domain.as.ctl.com/v2")
@XmlSeeAlso({
    com.ctl.as.domain.geo.types.ObjectFactory.class,
    com.ctl.as.domain.geo.types.request.ObjectFactory.class,
    com.ctl.as.domain.geo.v2.ObjectFactory.class,
    com.ctl.as.domain.geo.v2.types.ObjectFactory.class,
    com.ctl.as.domain.geo.v2.types.request.ObjectFactory.class,
    com.ctl.as.domain.geo.v2.types.response.ObjectFactory.class,
    com.iclnbi.iclnbi_v2_00.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    com.qwest.xmlschema.ObjectFactory.class,
    org.w3.namespace.ObjectFactory.class
})
public interface AddressServiceContract {


    /**
     * 
     * @param request
     * @return
     *     returns com.ctl.as.domain.geo.v2.types.response.IsThisAddressServiceableResponse
     */
    @WebMethod(operationName = "IsThisAddressServiceable", action = "http://geo.domain.as.ctl.com/v2/AddressServiceContract/IsThisAddressServiceable")
    @WebResult(name = "IsThisAddressServiceableResult", targetNamespace = "http://geo.domain.as.ctl.com/v2")
    @RequestWrapper(localName = "IsThisAddressServiceable", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.IsThisAddressServiceable")
    @ResponseWrapper(localName = "IsThisAddressServiceableResponse", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.IsThisAddressServiceableResponse")
    public IsThisAddressServiceableResponse isThisAddressServiceable(
        @WebParam(name = "request", targetNamespace = "http://geo.domain.as.ctl.com/v2")
        IsThisAddressServiceableRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.ctl.as.domain.geo.v2.types.response.GetServiceAddressResponse
     */
    @WebMethod(operationName = "GetServiceAddress", action = "http://geo.domain.as.ctl.com/v2/AddressServiceContract/GetServiceAddress")
    @WebResult(name = "GetServiceAddressResult", targetNamespace = "http://geo.domain.as.ctl.com/v2")
    @RequestWrapper(localName = "GetServiceAddress", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.GetServiceAddress")
    @ResponseWrapper(localName = "GetServiceAddressResponse", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.GetServiceAddressResponse")
    public GetServiceAddressResponse getServiceAddress(
        @WebParam(name = "request", targetNamespace = "http://geo.domain.as.ctl.com/v2")
        GetServiceAddressRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.ctl.as.domain.geo.v2.types.response.ValidateCivicAddressProxyResponse
     */
    @WebMethod(operationName = "ValidateCivicAddressProxy", action = "http://geo.domain.as.ctl.com/v2/AddressServiceContract/ValidateCivicAddressProxy")
    @WebResult(name = "ValidateCivicAddressProxyResult", targetNamespace = "http://geo.domain.as.ctl.com/v2")
    @RequestWrapper(localName = "ValidateCivicAddressProxy", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.ValidateCivicAddressProxy")
    @ResponseWrapper(localName = "ValidateCivicAddressProxyResponse", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.ValidateCivicAddressProxyResponse")
    public ValidateCivicAddressProxyResponse validateCivicAddressProxy(
        @WebParam(name = "request", targetNamespace = "http://geo.domain.as.ctl.com/v2")
        ValidateCivicAddressProxyRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.ctl.as.domain.geo.v2.types.response.GetSubAddressesResponse
     */
    @WebMethod(operationName = "GetSubAddresses", action = "http://geo.domain.as.ctl.com/v2/AddressServiceContract/GetSubAddresses")
    @WebResult(name = "GetSubAddressesResult", targetNamespace = "http://geo.domain.as.ctl.com/v2")
    @RequestWrapper(localName = "GetSubAddresses", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.GetSubAddresses")
    @ResponseWrapper(localName = "GetSubAddressesResponse", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.GetSubAddressesResponse")
    public GetSubAddressesResponse getSubAddresses(
        @WebParam(name = "request", targetNamespace = "http://geo.domain.as.ctl.com/v2")
        GetSubAddressesRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.ctl.as.domain.geo.v2.types.response.SubscriberAddressInquiryProxyResponse
     */
    @WebMethod(operationName = "SubscriberAddressInquiryProxy", action = "http://geo.domain.as.ctl.com/v2/AddressServiceContract/SubscriberAddressInquiryProxy")
    @WebResult(name = "SubscriberAddressInquiryProxyResult", targetNamespace = "http://geo.domain.as.ctl.com/v2")
    @RequestWrapper(localName = "SubscriberAddressInquiryProxy", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.SubscriberAddressInquiryProxy")
    @ResponseWrapper(localName = "SubscriberAddressInquiryProxyResponse", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.SubscriberAddressInquiryProxyResponse")
    public SubscriberAddressInquiryProxyResponse subscriberAddressInquiryProxy(
        @WebParam(name = "request", targetNamespace = "http://geo.domain.as.ctl.com/v2")
        SubscriberAddressInquiryProxyRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.ctl.as.domain.geo.v2.types.response.ClcSearchResourceProxyResponse
     */
    @WebMethod(operationName = "ClcSearchResourceProxy", action = "http://geo.domain.as.ctl.com/v2/AddressServiceContract/ClcSearchResourceProxy")
    @WebResult(name = "ClcSearchResourceProxyResult", targetNamespace = "http://geo.domain.as.ctl.com/v2")
    @RequestWrapper(localName = "ClcSearchResourceProxy", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.ClcSearchResourceProxy")
    @ResponseWrapper(localName = "ClcSearchResourceProxyResponse", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.ClcSearchResourceProxyResponse")
    public ClcSearchResourceProxyResponse clcSearchResourceProxy(
        @WebParam(name = "request", targetNamespace = "http://geo.domain.as.ctl.com/v2")
        ClcSearchResourceProxyRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.ctl.as.domain.geo.v2.types.response.GetParsedAddressResponse
     */
    @WebMethod(operationName = "GetParsedAddress", action = "http://geo.domain.as.ctl.com/v2/AddressServiceContract/GetParsedAddress")
    @WebResult(name = "GetParsedAddressResult", targetNamespace = "http://geo.domain.as.ctl.com/v2")
    @RequestWrapper(localName = "GetParsedAddress", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.GetParsedAddress")
    @ResponseWrapper(localName = "GetParsedAddressResponse", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.GetParsedAddressResponse")
    public GetParsedAddressResponse getParsedAddress(
        @WebParam(name = "request", targetNamespace = "http://geo.domain.as.ctl.com/v2")
        GetParsedAddressRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.ctl.as.domain.geo.v2.types.response.PostalAddressValidationResponse
     */
    @WebMethod(operationName = "PostalAddressValidation", action = "http://geo.domain.as.ctl.com/v2/AddressServiceContract/PostalAddressValidation")
    @WebResult(name = "PostalAddressValidationResult", targetNamespace = "http://geo.domain.as.ctl.com/v2")
    @RequestWrapper(localName = "PostalAddressValidation", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.PostalAddressValidation")
    @ResponseWrapper(localName = "PostalAddressValidationResponse", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.PostalAddressValidationResponse")
    public PostalAddressValidationResponse postalAddressValidation(
        @WebParam(name = "request", targetNamespace = "http://geo.domain.as.ctl.com/v2")
        PostalAddressValidationRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.ctl.as.domain.geo.v2.types.response.CivicAddressValidationResponse
     */
    @WebMethod(operationName = "CivicAddressValidation", action = "http://geo.domain.as.ctl.com/v2/AddressServiceContract/CivicAddressValidation")
    @WebResult(name = "CivicAddressValidationResult", targetNamespace = "http://geo.domain.as.ctl.com/v2")
    @RequestWrapper(localName = "CivicAddressValidation", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.CivicAddressValidation")
    @ResponseWrapper(localName = "CivicAddressValidationResponse", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.CivicAddressValidationResponse")
    public CivicAddressValidationResponse civicAddressValidation(
        @WebParam(name = "request", targetNamespace = "http://geo.domain.as.ctl.com/v2")
        CivicAddressValidationRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.ctl.as.domain.geo.v2.types.response.GetServiceAddressLiveResponse
     */
    @WebMethod(operationName = "GetServiceAddressLive", action = "http://geo.domain.as.ctl.com/v2/AddressServiceContract/GetServiceAddressLive")
    @WebResult(name = "GetServiceAddressLiveResult", targetNamespace = "http://geo.domain.as.ctl.com/v2")
    @RequestWrapper(localName = "GetServiceAddressLive", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.GetServiceAddressLive")
    @ResponseWrapper(localName = "GetServiceAddressLiveResponse", targetNamespace = "http://geo.domain.as.ctl.com/v2", className = "com.ctl.as.domain.geo.v2.GetServiceAddressLiveResponse")
    public GetServiceAddressLiveResponse getServiceAddressLive(
        @WebParam(name = "request", targetNamespace = "http://geo.domain.as.ctl.com/v2")
        GetServiceAddressLiveRequest request);

}
