package com.centurylink.pctl.mod.sfaint.modal;

/**
 * Created by dakshinamoorthyd on 02-12-2016.
 */
public enum SfaintStatusType {
    SFAINT_ACCOUNT_CREATION_INIT,
    SFAINT_ACCOUNT_CREATION_COMPLETED,
    SFAINT_ACCOUNT_CREATION_FAILED,

    SFAINT_CREATE_OPPURTUNITY_INIT,
    SFAINT_CREATE_OPPURTUNITY_COMPLETED,
    SFAINT_CREATE_OPPURTUNITY_FAILED,

    SFAINT_CREDIT_CHECK_INIT,
    SFAINT_CREDIT_CHECK_COMPLETED,
    SFAINT_CREDIT_CHECK_FAILED,

    SFAINT_CREATE_LEAD_INIT,
    SFAINT_CREATE_LEAD_COMPLETED,
    SFAINT_CREATE_LEAD_FAILED



}
