
package com.sforce.soap.schemas._class.ws_acq_leads;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WS_ACQ_LeadsPortType", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSACQLeadsPortType {


    /**
     * 
     * @param request
     * @param callOptions
     * @param sessionHeader
     * @param debuggingHeader
     * @param debuggingInfo
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.schemas._class.ws_acq_leads.ConvertLeadResponse
     */
    @WebMethod(operationName = "ConvertLead")
    @WebResult(name = "result", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
    @RequestWrapper(localName = "ConvertLead", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.ConvertLead")
    @ResponseWrapper(localName = "ConvertLeadResponse", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.ConvertLeadResponse2")
    public ConvertLeadResponse convertLead(
        @WebParam(name = "Request", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
        ConvertLeadRequest request,
        @WebParam(name = "SessionHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "CallOptions", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "CallOptions")
        CallOptions callOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo);

    /**
     * 
     * @param request
     * @param callOptions
     * @param sessionHeader
     * @param debuggingHeader
     * @param debuggingInfo
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.schemas._class.ws_acq_leads.ConvertLeadResponse
     */
    @WebMethod(operationName = "ConvertLeadMultiSite")
    @WebResult(name = "result", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
    @RequestWrapper(localName = "ConvertLeadMultiSite", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.ConvertLeadMultiSite")
    @ResponseWrapper(localName = "ConvertLeadMultiSiteResponse", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.ConvertLeadMultiSiteResponse")
    public ConvertLeadResponse convertLeadMultiSite(
        @WebParam(name = "Request", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
        ConvertLeadRequest request,
        @WebParam(name = "SessionHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "CallOptions", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "CallOptions")
        CallOptions callOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo);

    /**
     * 
     * @param request
     * @param callOptions
     * @param sessionHeader
     * @param debuggingHeader
     * @param debuggingInfo
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.schemas._class.ws_acq_leads.CreateLeadResponse
     */
    @WebMethod(operationName = "CreateLeads")
    @WebResult(name = "result", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
    @RequestWrapper(localName = "CreateLeads", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.CreateLeads")
    @ResponseWrapper(localName = "CreateLeadsResponse", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.CreateLeadsResponse")
    public CreateLeadResponse createLeads(
        @WebParam(name = "Request", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
        CreateLeadRequest request,
        @WebParam(name = "SessionHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "CallOptions", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "CallOptions")
        CallOptions callOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo);

    /**
     * 
     * @param request
     * @param callOptions
     * @param sessionHeader
     * @param debuggingHeader
     * @param debuggingInfo
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.schemas._class.ws_acq_leads.CreateLeadResponse
     */
    @WebMethod(operationName = "CreateLeadsMultiSite")
    @WebResult(name = "result", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
    @RequestWrapper(localName = "CreateLeadsMultiSite", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.CreateLeadsMultiSite")
    @ResponseWrapper(localName = "CreateLeadsMultiSiteResponse", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.CreateLeadsMultiSiteResponse")
    public CreateLeadResponse createLeadsMultiSite(
        @WebParam(name = "Request", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
        CreateLeadRequestMultiSite request,
        @WebParam(name = "SessionHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "CallOptions", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "CallOptions")
        CallOptions callOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo);

    /**
     * 
     * @param callOptions
     * @param cuid
     * @param sessionHeader
     * @param debuggingHeader
     * @param debuggingInfo
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.schemas._class.ws_acq_leads.UserResponse
     */
    @WebMethod(operationName = "CUIDStatus")
    @WebResult(name = "result", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
    @RequestWrapper(localName = "CUIDStatus", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.CUIDStatus")
    @ResponseWrapper(localName = "CUIDStatusResponse", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.CUIDStatusResponse")
    public UserResponse cuidStatus(
        @WebParam(name = "cuid", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
        String cuid,
        @WebParam(name = "SessionHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "CallOptions", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "CallOptions")
        CallOptions callOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo);

    /**
     * 
     * @param request
     * @param callOptions
     * @param sessionHeader
     * @param debuggingHeader
     * @param debuggingInfo
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.schemas._class.ws_acq_leads.CompanyQualifiedLocResponse
     */
    @WebMethod(operationName = "GetCompanyQualifiedLocations")
    @WebResult(name = "result", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
    @RequestWrapper(localName = "GetCompanyQualifiedLocations", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.GetCompanyQualifiedLocations")
    @ResponseWrapper(localName = "GetCompanyQualifiedLocationsResponse", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.GetCompanyQualifiedLocationsResponse")
    public CompanyQualifiedLocResponse getCompanyQualifiedLocations(
        @WebParam(name = "request", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
        CompanyQualifiedLocRequest request,
        @WebParam(name = "SessionHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "CallOptions", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "CallOptions")
        CallOptions callOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo);

    /**
     * 
     * @param request
     * @param callOptions
     * @param sessionHeader
     * @param debuggingHeader
     * @param debuggingInfo
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.schemas._class.ws_acq_leads.CompanyQualifiedtntResponse
     */
    @WebMethod(operationName = "GetCQLTenants")
    @WebResult(name = "result", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
    @RequestWrapper(localName = "GetCQLTenants", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.GetCQLTenants")
    @ResponseWrapper(localName = "GetCQLTenantsResponse", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.GetCQLTenantsResponse")
    public CompanyQualifiedtntResponse getCQLTenants(
        @WebParam(name = "request", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
        CompanyQualifiedLocTntRequest request,
        @WebParam(name = "SessionHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "CallOptions", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "CallOptions")
        CallOptions callOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo);

    /**
     * 
     * @param request
     * @param callOptions
     * @param sessionHeader
     * @param debuggingHeader
     * @param debuggingInfo
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.schemas._class.ws_acq_leads.GetLeadResponse
     */
    @WebMethod(operationName = "GetLeads")
    @WebResult(name = "result", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
    @RequestWrapper(localName = "GetLeads", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.GetLeads")
    @ResponseWrapper(localName = "GetLeadsResponse", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.GetLeadsResponse")
    public GetLeadResponse getLeads(
        @WebParam(name = "Request", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
        GetLeadRequest request,
        @WebParam(name = "SessionHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "CallOptions", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "CallOptions")
        CallOptions callOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo);

    /**
     * 
     * @param request
     * @param callOptions
     * @param sessionHeader
     * @param debuggingHeader
     * @param debuggingInfo
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.schemas._class.ws_acq_leads.GetLeadResponseMultiSite
     */
    @WebMethod(operationName = "GetLeadsMultiSite")
    @WebResult(name = "result", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
    @RequestWrapper(localName = "GetLeadsMultiSite", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.GetLeadsMultiSite")
    @ResponseWrapper(localName = "GetLeadsMultiSiteResponse", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.GetLeadsMultiSiteResponse")
    public GetLeadResponseMultiSite getLeadsMultiSite(
        @WebParam(name = "Request", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
        GetLeadRequest request,
        @WebParam(name = "SessionHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "CallOptions", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "CallOptions")
        CallOptions callOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo);

    /**
     * 
     * @param request
     * @param callOptions
     * @param sessionHeader
     * @param debuggingHeader
     * @param debuggingInfo
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.schemas._class.ws_acq_leads.GetOpportunityResponse
     */
    @WebMethod(operationName = "GetOpportunities")
    @WebResult(name = "result", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
    @RequestWrapper(localName = "GetOpportunities", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.GetOpportunities")
    @ResponseWrapper(localName = "GetOpportunitiesResponse", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.GetOpportunitiesResponse")
    public GetOpportunityResponse getOpportunities(
        @WebParam(name = "Request", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
        GetopportunityRequest request,
        @WebParam(name = "SessionHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "CallOptions", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "CallOptions")
        CallOptions callOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo);

    /**
     * 
     * @param callOptions
     * @param sessionHeader
     * @param debuggingHeader
     * @param debuggingInfo
     * @param seqId
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.schemas._class.ws_acq_leads.ReturnCustomersResponse
     */
    @WebMethod(operationName = "ReturnCustomer")
    @WebResult(name = "result", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
    @RequestWrapper(localName = "ReturnCustomer", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.ReturnCustomer")
    @ResponseWrapper(localName = "ReturnCustomerResponse", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.ReturnCustomerResponse")
    public ReturnCustomersResponse returnCustomer(
        @WebParam(name = "SeqId", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
        String seqId,
        @WebParam(name = "SessionHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "CallOptions", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "CallOptions")
        CallOptions callOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo);

    /**
     * 
     * @param request
     * @param callOptions
     * @param sessionHeader
     * @param debuggingHeader
     * @param debuggingInfo
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.schemas._class.ws_acq_leads.SearchByAccountIdResponse2
     */
    @WebMethod(operationName = "SearchByAccountId")
    @WebResult(name = "result", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
    @RequestWrapper(localName = "SearchByAccountId", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.SearchByAccountId")
    @ResponseWrapper(localName = "SearchByAccountIdResponse", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.SearchByAccountIdResponse")
    public SearchByAccountIdResponse2 searchByAccountId(
        @WebParam(name = "request", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
        SearchByAccountIdRequest request,
        @WebParam(name = "SessionHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "CallOptions", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "CallOptions")
        CallOptions callOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo);

    /**
     * 
     * @param request
     * @param callOptions
     * @param sessionHeader
     * @param debuggingHeader
     * @param debuggingInfo
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.schemas._class.ws_acq_leads.CustomerSearchResponse
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
    @RequestWrapper(localName = "searchByCustomerName", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.SearchByCustomerName")
    @ResponseWrapper(localName = "searchByCustomerNameResponse", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.SearchByCustomerNameResponse")
    public CustomerSearchResponse searchByCustomerName(
        @WebParam(name = "request", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
        CustomerSearchRequest request,
        @WebParam(name = "SessionHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "CallOptions", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "CallOptions")
        CallOptions callOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo);

    /**
     * 
     * @param request
     * @param callOptions
     * @param sessionHeader
     * @param debuggingHeader
     * @param debuggingInfo
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.schemas._class.ws_acq_leads.UpdateLeadsResponse2
     */
    @WebMethod(operationName = "UpdateLeads")
    @WebResult(name = "result", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
    @RequestWrapper(localName = "UpdateLeads", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.UpdateLeads")
    @ResponseWrapper(localName = "UpdateLeadsResponse", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.UpdateLeadsResponse")
    public UpdateLeadsResponse2 updateLeads(
        @WebParam(name = "Request", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
        UpdateLeadsRequest request,
        @WebParam(name = "SessionHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "CallOptions", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "CallOptions")
        CallOptions callOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo);

    /**
     * 
     * @param request
     * @param callOptions
     * @param sessionHeader
     * @param debuggingHeader
     * @param debuggingInfo
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.schemas._class.ws_acq_leads.UpdateLeadsResponse2
     */
    @WebMethod(operationName = "UpdateLeadsMultiSite")
    @WebResult(name = "result", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
    @RequestWrapper(localName = "UpdateLeadsMultiSite", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.UpdateLeadsMultiSite")
    @ResponseWrapper(localName = "UpdateLeadsMultiSiteResponse", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.UpdateLeadsMultiSiteResponse")
    public UpdateLeadsResponse2 updateLeadsMultiSite(
        @WebParam(name = "Request", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
        UpdateLeadsRequestMultiSite request,
        @WebParam(name = "SessionHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "CallOptions", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "CallOptions")
        CallOptions callOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo);

    /**
     * 
     * @param callOptions
     * @param sessionHeader
     * @param debuggingHeader
     * @param debuggingInfo
     * @param userId
     * @param allowFieldTruncationHeader
     * @return
     *     returns com.sforce.soap.schemas._class.ws_acq_leads.UserResponse
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
    @RequestWrapper(localName = "userStatus", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.UserStatus")
    @ResponseWrapper(localName = "userStatusResponse", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", className = "com.sforce.soap.schemas._class.ws_acq_leads.UserStatusResponse")
    public UserResponse userStatus(
        @WebParam(name = "userId", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads")
        String userId,
        @WebParam(name = "SessionHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "SessionHeader")
        SessionHeader sessionHeader,
        @WebParam(name = "CallOptions", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "CallOptions")
        CallOptions callOptions,
        @WebParam(name = "DebuggingHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "DebuggingHeader")
        DebuggingHeader debuggingHeader,
        @WebParam(name = "AllowFieldTruncationHeader", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, partName = "AllowFieldTruncationHeader")
        AllowFieldTruncationHeader allowFieldTruncationHeader,
        @WebParam(name = "DebuggingInfo", targetNamespace = "http://soap.sforce.com/schemas/class/WS_ACQ_Leads", header = true, mode = WebParam.Mode.OUT, partName = "DebuggingInfo")
        Holder<DebuggingInfo> debuggingInfo);

}
