
package com.ctl.ecaps.service.useradmin;

import javax.xml.ws.WebFault;
import com.ctl.ecaps.serviceobject.FaultDetailSO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ServiceSystemException", targetNamespace = "http://ecaps.ctl.com/exceptions")
public class ServiceSystemException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultDetailSO faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ServiceSystemException(String message, FaultDetailSO faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ServiceSystemException(String message, FaultDetailSO faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ctl.ecaps.serviceobject.FaultDetailSO
     */
    public FaultDetailSO getFaultInfo() {
        return faultInfo;
    }

}
