
package com.ctl.ecaps.service.useradmin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserAdminService", targetNamespace = "http://ecaps.ctl.com/service/userAdmin", wsdlLocation = "file:/C:/1PCenturyLink/WSDLs/Real-WSDLs/UserAdminService.xml")
public class UserAdminService_Service
    extends Service
{

    private final static URL USERADMINSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERADMINSERVICE_EXCEPTION;
    private final static QName USERADMINSERVICE_QNAME = new QName("http://ecaps.ctl.com/service/userAdmin", "UserAdminService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/1PCenturyLink/WSDLs/Real-WSDLs/UserAdminService.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERADMINSERVICE_WSDL_LOCATION = url;
        USERADMINSERVICE_EXCEPTION = e;
    }

    public UserAdminService_Service() {
        super(__getWsdlLocation(), USERADMINSERVICE_QNAME);
    }

    public UserAdminService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERADMINSERVICE_QNAME, features);
    }

    public UserAdminService_Service(URL wsdlLocation) {
        super(wsdlLocation, USERADMINSERVICE_QNAME);
    }

    public UserAdminService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERADMINSERVICE_QNAME, features);
    }

    public UserAdminService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserAdminService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserAdminService
     */
    @WebEndpoint(name = "UserAdminServicePort")
    public UserAdminService getUserAdminServicePort() {
        return super.getPort(new QName("http://ecaps.ctl.com/service/userAdmin", "UserAdminServicePort"), UserAdminService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserAdminService
     */
    @WebEndpoint(name = "UserAdminServicePort")
    public UserAdminService getUserAdminServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ecaps.ctl.com/service/userAdmin", "UserAdminServicePort"), UserAdminService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERADMINSERVICE_EXCEPTION!= null) {
            throw USERADMINSERVICE_EXCEPTION;
        }
        return USERADMINSERVICE_WSDL_LOCATION;
    }

}
