
package com.ctl.ecaps.service.enterpriseadmin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EnterpriseAdminService", targetNamespace = "http://ecaps.ctl.com/service/enterpriseAdmin", wsdlLocation = "file:/C:/1PCenturyLink/WSDLs/Real-WSDLs/EnterpriseAdminService.xml")
public class EnterpriseAdminService_Service
    extends Service
{

    private final static URL ENTERPRISEADMINSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENTERPRISEADMINSERVICE_EXCEPTION;
    private final static QName ENTERPRISEADMINSERVICE_QNAME = new QName("http://ecaps.ctl.com/service/enterpriseAdmin", "EnterpriseAdminService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/1PCenturyLink/WSDLs/Real-WSDLs/EnterpriseAdminService.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENTERPRISEADMINSERVICE_WSDL_LOCATION = url;
        ENTERPRISEADMINSERVICE_EXCEPTION = e;
    }

    public EnterpriseAdminService_Service() {
        super(__getWsdlLocation(), ENTERPRISEADMINSERVICE_QNAME);
    }

    public EnterpriseAdminService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENTERPRISEADMINSERVICE_QNAME, features);
    }

    public EnterpriseAdminService_Service(URL wsdlLocation) {
        super(wsdlLocation, ENTERPRISEADMINSERVICE_QNAME);
    }

    public EnterpriseAdminService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENTERPRISEADMINSERVICE_QNAME, features);
    }

    public EnterpriseAdminService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnterpriseAdminService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EnterpriseAdminService
     */
    @WebEndpoint(name = "EnterpriseAdminServicePort")
    public EnterpriseAdminService getEnterpriseAdminServicePort() {
        return super.getPort(new QName("http://ecaps.ctl.com/service/enterpriseAdmin", "EnterpriseAdminServicePort"), EnterpriseAdminService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnterpriseAdminService
     */
    @WebEndpoint(name = "EnterpriseAdminServicePort")
    public EnterpriseAdminService getEnterpriseAdminServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ecaps.ctl.com/service/enterpriseAdmin", "EnterpriseAdminServicePort"), EnterpriseAdminService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENTERPRISEADMINSERVICE_EXCEPTION!= null) {
            throw ENTERPRISEADMINSERVICE_EXCEPTION;
        }
        return ENTERPRISEADMINSERVICE_WSDL_LOCATION;
    }

}
